### ISSUE TITLE
Display something when nothing found

### ISSUE THREAD

**Issue by AlexWayfer** [Ademking/Coub-Music-Finder#1]
Hello.

It'd be nice to know when service can't find anything.

Example:

![image](https://user-images.githubusercontent.com/6510020/116384633-b9873d80-a820-11eb-9a5d-329ab61f318c.png)

Reference from the alternative:

![image](https://user-images.githubusercontent.com/6510020/116384721-cc017700-a820-11eb-89e7-4a038ae26e83.png)

**Comment by Ademking** [comment]
Thank you so much for your suggestion. This project is 3 years old and it's unmaintained (I was learning React :smile: )
If you want, please contribute to this project.

**Comment by AlexWayfer** [comment]
1. We can add a note about abandoning.
2. It's OK, and I can try, but I don't understand why you did close the issue if it's still here and my (or any other) PR can close it (actually close, resolve).
